// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UnitMonitoringSystem.Infrastructure.Data;

namespace UnitMonitoringSystem.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("UnitMonitoringSystem.Core.Entities.Instance", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Modified")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Instances");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "An item collection for recording aquatic species and vegetation",
                            Modified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "My Aquarium"
                        },
                        new
                        {
                            ID = 2,
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Things we should probably take care of at some point",
                            Modified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "To-Do List"
                        },
                        new
                        {
                            ID = 3,
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Hey there Hercules! What do you bench? How many reps? Let the gym know!",
                            Modified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Gymnasium"
                        });
                });

            modelBuilder.Entity("UnitMonitoringSystem.Core.Entities.Unit", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("InstanceId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Modified")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("InstanceId");

                    b.ToTable("Units");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Created = new DateTime(2020, 11, 9, 22, 13, 56, 830, DateTimeKind.Local).AddTicks(4414),
                            Description = "Description 1",
                            InstanceId = 1,
                            Modified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Generic Unit 1"
                        },
                        new
                        {
                            ID = 2,
                            Created = new DateTime(2020, 11, 10, 22, 13, 56, 833, DateTimeKind.Local).AddTicks(7302),
                            Description = "Description 2",
                            InstanceId = 1,
                            Modified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Generic Unit 2"
                        },
                        new
                        {
                            ID = 3,
                            Created = new DateTime(2020, 11, 11, 22, 13, 56, 833, DateTimeKind.Local).AddTicks(7361),
                            Description = "Description 3",
                            InstanceId = 1,
                            Modified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Generic Unit 3"
                        },
                        new
                        {
                            ID = 4,
                            Created = new DateTime(2020, 11, 12, 22, 13, 56, 833, DateTimeKind.Local).AddTicks(7367),
                            Description = "Description 4",
                            InstanceId = 1,
                            Modified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Generic Unit 4"
                        },
                        new
                        {
                            ID = 5,
                            Created = new DateTime(2020, 11, 13, 22, 13, 56, 833, DateTimeKind.Local).AddTicks(7371),
                            Description = "Description 5",
                            InstanceId = 1,
                            Modified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Generic Unit 5"
                        },
                        new
                        {
                            ID = 6,
                            Created = new DateTime(2020, 11, 14, 22, 13, 56, 833, DateTimeKind.Local).AddTicks(7374),
                            Description = "Description 6",
                            InstanceId = 1,
                            Modified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Generic Unit 6"
                        },
                        new
                        {
                            ID = 7,
                            Created = new DateTime(2020, 11, 15, 22, 13, 56, 833, DateTimeKind.Local).AddTicks(7377),
                            Description = "Description 7",
                            InstanceId = 1,
                            Modified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Generic Unit 7"
                        },
                        new
                        {
                            ID = 8,
                            Created = new DateTime(2020, 11, 16, 22, 13, 56, 833, DateTimeKind.Local).AddTicks(7380),
                            Description = "Description 8",
                            InstanceId = 1,
                            Modified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Generic Unit 8"
                        },
                        new
                        {
                            ID = 9,
                            Created = new DateTime(2020, 11, 17, 22, 13, 56, 833, DateTimeKind.Local).AddTicks(7383),
                            Description = "Description 9",
                            InstanceId = 1,
                            Modified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Generic Unit 9"
                        },
                        new
                        {
                            ID = 10,
                            Created = new DateTime(2020, 11, 18, 22, 13, 56, 833, DateTimeKind.Local).AddTicks(7386),
                            Description = "Description 10",
                            InstanceId = 1,
                            Modified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Generic Unit 10"
                        },
                        new
                        {
                            ID = 11,
                            Created = new DateTime(2020, 11, 9, 22, 13, 56, 833, DateTimeKind.Local).AddTicks(7389),
                            Description = "Description 1",
                            InstanceId = 2,
                            Modified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Generic Unit 1"
                        },
                        new
                        {
                            ID = 12,
                            Created = new DateTime(2020, 11, 10, 22, 13, 56, 833, DateTimeKind.Local).AddTicks(7392),
                            Description = "Description 2",
                            InstanceId = 2,
                            Modified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Generic Unit 2"
                        },
                        new
                        {
                            ID = 13,
                            Created = new DateTime(2020, 11, 11, 22, 13, 56, 833, DateTimeKind.Local).AddTicks(7396),
                            Description = "Description 3",
                            InstanceId = 2,
                            Modified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Generic Unit 3"
                        },
                        new
                        {
                            ID = 14,
                            Created = new DateTime(2020, 11, 9, 22, 13, 56, 833, DateTimeKind.Local).AddTicks(7399),
                            Description = "Description 1",
                            InstanceId = 3,
                            Modified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Generic Unit 1"
                        },
                        new
                        {
                            ID = 15,
                            Created = new DateTime(2020, 11, 10, 22, 13, 56, 833, DateTimeKind.Local).AddTicks(7402),
                            Description = "Description 2",
                            InstanceId = 3,
                            Modified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Generic Unit 2"
                        },
                        new
                        {
                            ID = 16,
                            Created = new DateTime(2020, 11, 11, 22, 13, 56, 833, DateTimeKind.Local).AddTicks(7405),
                            Description = "Description 3",
                            InstanceId = 3,
                            Modified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Generic Unit 3"
                        });
                });

            modelBuilder.Entity("UnitMonitoringSystem.Core.Entities.Unit", b =>
                {
                    b.HasOne("UnitMonitoringSystem.Core.Entities.Instance", "Instance")
                        .WithMany("Units")
                        .HasForeignKey("InstanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Instance");
                });

            modelBuilder.Entity("UnitMonitoringSystem.Core.Entities.Instance", b =>
                {
                    b.Navigation("Units");
                });
#pragma warning restore 612, 618
        }
    }
}
